trigger: none

stages:
  - stage: deploy
    jobs:
      - deployment: starbucksDeploy
        environment:
         name: dev
        strategy: 
         runOnce:
           deploy:
             steps:
             - task: CmdLine@2
               inputs:
                 script: 'sudo mkdir -p /app'