trigger: none

stages:
  - stage: deploy
    jobs:
      - deployment: starbucksDeploy
        environment: dev
        strategy: 
         runOnce:
           deploy:
             steps:
             - task: CmdLine@2
               inputs:
                 script: 'cp -r $(System.DefaultWorkingDirectory)/ /tmp'